name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login dockerhub.petrmikolas.cz -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build . -f ./Notebook/Dockerfile -t dockerhub.petrmikolas.cz/notebook:latest

    - name: Push Docker image to Docker Hub
      run: docker push dockerhub.petrmikolas.cz/notebook:latest

    - name: Copy compose.yaml to NAS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.NAS_HOST }}
        username: ${{ secrets.NAS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.NAS_PORT }}
        source: "./compose.yaml"
        target: "/volume1/docker/notebook/"

    - name: Deploy on NAS
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.NAS_HOST }}
        username: ${{ secrets.NAS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.NAS_PORT }}
        script: |
          set -e
          
          echo "Changing to target directory on NAS"
          cd /volume1/docker/notebook

          echo "Stopping existing containers (if any)"
          /usr/local/bin/docker-compose -f compose.yaml down || true

          echo "Removing orphaned containers"
          /usr/local/bin/docker ps -aq --filter "name=investment-portfolio" | xargs -r /usr/local/bin/docker rm || true

          echo "Removing old Docker images"
          old_images=$(/usr/local/bin/docker images -q dockerhub.petrmikolas.cz/notebook:latest)
          [ -n "$old_images" ] && /usr/local/bin/docker rmi -f $old_images || true

          echo "Pulling latest image from Docker Hub"
          /usr/local/bin/docker pull dockerhub.petrmikolas.cz/notebook:latest

          echo "Starting new containers"
          /usr/local/bin/docker-compose -f compose.yaml up -d

          echo "Deployment completed successfully."
